save_dir: runs_homeplate/train/yolov9-c
weights: yolov9-c.pt
cfg: /opt/conda/envs/baseballcv/lib/python3.11/site-packages/yolov9/models/detect/yolov9-c.yaml
data: homeplate_dataset/data.yaml
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  dfl: 1.5
  iou_t: 0.2
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.9
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.15
  copy_paste: 0.3
epochs: 50
batch_size: 12
imgsz: 800
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0
multi_scale: false
single_cls: true
optimizer: SGD
sync_bn: true
workers: 4
project: runs_homeplate/train
name: yolov9-c
exist_ok: true
quad: false
cos_lr: true
flat_cos_lr: false
fixed_lr: false
label_smoothing: 0.2
patience: 20
freeze:
- 0
save_period: -1
seed: 38
local_rank: -1
min_items: 0
close_mosaic: 0
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
