# docs/_config.yml
title: BaseballCV Documentation
description: Documentation for BaseballCV - Computer Vision Tools for Baseball Analytics
baseurl: "/BaseballCV"
url: "https://dylandru.github.io"

# Theme configuration
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme settings
search_enabled: true
heading_anchors: true
color_scheme: light

# Aux links for upper right navigation
aux_links:
  "BaseballCV on GitHub":
    - "//github.com/dylandru/BaseballCV"

aux_links_new_tab: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 BaseballCV. Distributed under an MIT license."

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      nav_order: 1