# docs/_config.yml
title: BaseballCV Documentation
description: Documentation for BaseballCV - Computer Vision Tools for Baseball Analytics
baseurl: "/BaseballCV"
url: "https://dylandru.github.io"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Theme settings
search_enabled: true
heading_anchors: true
color_scheme: light

# Navigation
aux_links:
  "BaseballCV on GitHub":
    - "//github.com/dylandru/BaseballCV"

# Collections
collections:
  pages:
    permalink: "/:collection/:path/"
    output: true

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default