remote_theme: just-the-docs/just-the-docs
title: BaseballCV Documentation
description: Documentation for the BaseballCV computer vision toolkit
baseurl: "/BaseballCV"
url: "https://dylandru.github.io"

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Navigation
nav_external_links:
  - title: BaseballCV on GitHub
    url: https://github.com/dylandru/BaseballCV
    hide_icon: false

aux_links:
  "View on GitHub":
    - "//github.com/dylandru/BaseballCV"

# Footer
footer_content: "Copyright &copy; 2024 Dylan Drummey, Carlos Marcano. Distributed under an MIT license."

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation