name: Build and Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        
    - name: Build package
      run: |
        python -m build
        
    - name: Create test directory
      run: mkdir test_dir
      
    - name: Run tests with network-dependent tests skipped
      run: |
        # Run tests with environment variable to skip network-dependent tests
        SKIP_NETWORK_TESTS=1 pytest tests/ -v --ignore=tests/test_api/ --ignore=tests/test_datasets/test_datasets_jsonl_detection.py
      continue-on-error: true
        
    - name: Upload distribution to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/