name: Package Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Install Poetry & dependencies
      run: |
        pip install poetry
        poetry install --with dev

    - name: Build package using Poetry
      run: poetry build

    - name: Run tests
      run: |
        # Run tests with environment variable to skip network-dependent tests
        poetry run SKIP_NETWORK_TESTS=1 pytest tests/ -v --ignore=tests/test_api/ --ignore=tests/test_datasets/test_datasets_jsonl_detection.py
  

    - name: Upload distribution to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions-${{ matrix.python-version }}
        path: dist/